# Generated by Django 2.2.5 on 2021-01-28 01:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Action', 'Action'), ('Anime', 'Anime'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction')], max_length=60)),
                ('Movie_Title', models.CharField(blank=True, default='', max_length=60)),
                ('Starring', models.CharField(blank=True, default='', max_length=60)),
                ('Directed_By', models.CharField(blank=True, default='', max_length=60)),
                ('Year_Released', models.IntegerField(default='')),
            ],
            managers=[
                ('add_movies', django.db.models.manager.Manager()),
            ],
        ),
    ]
