# Generated by Django 2.2.5 on 2021-01-28 20:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movies',
            managers=[
                ('addMovies', django.db.models.manager.Manager()),
            ],
        ),
    ]
