# Generated by Django 2.2.5 on 2021-01-28 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210128_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='type',
            new_name='Genre',
        ),
    ]
